version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/my-wonderland
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - my-wonderland-network
    php:
        image: php:7-fpm
        volumes:
            - .:/var/www/my-wonderland
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - my-wonderland-network
    composer:
        image: composer:latest
        volumes:
          - .:/app
        command: 'true'
networks:
    my-wonderland-network:
        driver: bridge
